import SupportHerin from '../components/common/SupportHerin';
import React, {useEffect} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen, ShieldCheck, ArrowRight} from 'lucide-react';
import '../styles/info.css';

const guide = [
  ['Share a study snapshot', 'Select Share on an open lesson, note, flashcard, or quiz question. Review the public preview and choose what to include, then select Create & copy link. Anyone with the link can read it without signing in. Edits do not change existing snapshots. In Settings, use Shared study links to stop sharing. Deleting the source also disables its link.'],
  ['Start your workspace', 'Create an account, confirm it using the email you receive, and log in. Check your spam folder if the email is missing. Use the same account on your other devices to access saved study materials.'],
  ['Plan classes and assignments', 'Open My Schedule to add classes. Choose the correct weekdays, start and end times, and any instructor or location details. Add assignments with their due dates and mark them complete as you finish. Check your device’s time zone when setting up your schedule.'],
  ['Upload and read a PDF', 'In My PDFs, import a PDF and wait for processing and saving to finish. Open the document to change pages, zoom, or fit the page to the reader. Use Download original to keep a separate copy. Text-based PDFs work best; scanned pages may not provide extractable text.'],
  ['Organize notes and highlights', 'Give your PDF a subject to organize it in the sidebar. Select lesson text and choose a highlight color. Use the Extracted text, My notes, and Highlights tabs beside the reader to review your material. The Notes page brings your notes together. Refresh extracted notes reads the PDF again; it is separate from AI generation.'],
  ['Use AI Herin Assistant', 'Open a PDF and select AI Herin Assistant in its toolbar. Choose your PDF, an optional class, an entire-PDF or page-range topic, the number of items, and difficulty. Select Generate Flashcards, Generate Quiz, Generate Both, or Summarize topic. Wait for the result before starting another request, then review the saved materials in Flashcards or Quiz. Generation needs an internet connection and readable lesson text. Always check answers against the source.'],
  ['Practice with flashcards and quizzes', 'Open Flashcards, select a card, and reveal its answer before reviewing it. Use the source links to revisit the lesson. In Quiz, answer each question and review the feedback. You can edit or delete study items when a generated answer needs correcting.'],
  ['Set up class reminders', 'In Settings, turn on reminders, select how many minutes before class to be notified, and enable background reminders on each device. Allow browser notifications and send a test. A successful test checks delivery; scheduled reminders also need saved class days and times. On iPhone or iPad, add Herin to your Home Screen and open it there to enable supported push notifications.'],
  ['Make Herin yours', 'Use Settings to choose light, dark, or system appearance, an accent theme, and your display name. Wait for Saved to Supabase before closing the app after changes.'],
  ['Keep a copy and work offline', 'Settings lets you export workspace data as JSON. This export does not contain original PDF files; download those separately. Previously cached materials may be available offline, while AI generation and cloud uploads need a connection. Reconnect and wait for syncing before clearing browser data or switching devices.'],
];
const policy = [
  ['Public study links', 'Sharing is optional. When you create a study link, the title, subject, and content shown in the share preview are stored as a public snapshot. Anyone with the link can view and forward it without signing in. Your account details, review progress, and original PDF file are not included. You can stop sharing in Settings; deleting the source also disables the link. Recipients may retain their own copies.'],
  ['Who operates Herin', <>Herin is operated by its owner, who can be contacted at <a href="mailto:johnbenedictbucao2@gmail.com">johnbenedictbucao2@gmail.com</a>. This policy describes how the Herin website and app handle your information.</>],
  ['Information Herin handles', 'Herin uses your account email and authentication information to sign you in. Your workspace can include a display name, PDFs, extracted text, notes, highlights, flashcards, quizzes and results, classes, assignments, reminders, and preferences. These are used to provide your study workspace and synchronize it across devices.'],
  ['Storage and access', 'Supabase provides account authentication, the database, and private PDF storage. Workspace access is restricted by account ownership rules. Hosting, database, and service operators may process information to operate, support, and secure the service. Private storage is not end-to-end encryption. Only upload material you are entitled to use.'],
  ['AI processing', <>When you request AI generation, Herin sends extracted text from the selected lesson or page range, along with generation instructions, to Google’s Gemini API. Generated results are saved in your workspace. Google’s handling depends on the applicable service tier and terms; unpaid services may use inputs and outputs for product improvement and human review. Do not include sensitive, confidential, or personal information in AI requests. Read the <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer">Gemini API terms</a> for details.</>],
  ['Browser storage and offline copies', 'Herin stores session information and workspace caches in your browser and may cache PDFs and app files for offline access. Logging out ends your session but does not guarantee removal of every cached file. On a shared device, log out and clear Herin’s site data after confirming that your changes are saved. Clearing site data can remove unsynced work and offline copies.'],
  ['Optional notifications', 'If you enable background reminders, Herin stores your device’s push subscription, delivery keys, and time zone so reminders can be delivered through your browser’s push service. Reminder content may appear on your lock screen. Disable reminders in Settings or revoke notification permission in your browser to stop alerts. Delivery can be affected by device, network, and operating-system settings.'],
  ['Service providers', <>Herin is hosted on Vercel and uses Supabase and Google Gemini for the functions described here. These providers may process operational information, such as network requests and error logs, and may process data in other countries. Their policies explain their own practices: <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel</a>, <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">Supabase</a>, and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google</a>.</>],
  ['Your controls and deletion', <>You can edit or delete study items, export workspace data in Settings, download original PDFs, and disable notifications. Clear data resets your study workspace; it does not delete your sign-in account. Export your work and download PDFs first if you want to keep them. For account deletion, access, correction, or other privacy requests, email <a href="mailto:johnbenedictbucao2@gmail.com">johnbenedictbucao2@gmail.com</a>. The owner may need to verify that the account belongs to you. Never send your password.</>],
  ['Retention', 'Saved workspace information remains available until it is removed through the app or by the owner. Browser copies remain until removed or evicted by your browser. Removing active records may not immediately remove provider backups or operational logs, which follow the relevant provider’s retention practices.'],
  ['Policy updates', 'This page will be updated when Herin’s data practices change. Check the date above for the latest revision. For questions about this policy, use the owner’s contact email above.'],
];
export default function InfoPage({privacy=false}) {
  const title=privacy?'Privacy policy':'How to use Herin';
  useEffect(()=>{document.title=`${title} · Herin`;window.scrollTo(0,0);return()=>{document.title='Herin';};},[title]);
  const Icon=privacy?ShieldCheck:BookOpen;
  return <div className="info-shell"><header className="info-header"><Link to="/" className="info-brand"><img src={`${import.meta.env.BASE_URL}herin-logo.svg`} width="36" height="36" alt=""/>Herin</Link><Link to="/" className="btn btn-secondary">Open workspace <ArrowRight size={16} aria-hidden="true"/></Link></header><main className="info-main"><nav className="info-tabs" aria-label="Help pages"><Link to="/guide" aria-current={!privacy?'page':undefined}>User guide</Link><Link to="/privacy" aria-current={privacy?'page':undefined}>Privacy policy</Link></nav><div className="info-intro"><span className="info-emblem"><Icon size={26} aria-hidden="true"/></span><h1>{title}</h1><p>{privacy?'Understand what is stored, when information is shared, and the controls available to you.':'From your first PDF to your next study session. A practical guide to your learning workspace.'}</p>{privacy&&<small>Last updated: October 1, 2026</small>}</div>{!privacy&&<aside className="info-callout"><strong>A simple study routine</strong><p>Upload a PDF → read and highlight → generate study materials → practice → review the source.</p></aside>}<div className="info-sections">{(privacy?policy:guide).map(([heading,body],i)=><section className="info-section" key={heading}>{!privacy&&<span className="info-step" aria-hidden="true">{String(i+1).padStart(2,'0')}</span>}<div><h2>{heading}</h2><p>{body}</p></div></section>)}</div>{!privacy&&<section className="info-callout"><h2>Something not working?</h2><p>If study materials are empty, open the PDF and check the AI generation result before retrying. If a save fails, reconnect and retry syncing. For missed class reminders, check the class weekday, time zone, reminder lead time, and device permission. Notifications are best-effort and cannot be guaranteed at an exact time.</p></section>}<footer className="info-footer"><SupportHerin/><span>Herin · Your learning space</span><Link to={privacy?'/guide':'/privacy'}>{privacy?'Read the user guide':'Read the privacy policy'} <ArrowRight size={15} aria-hidden="true"/></Link></footer></main></div>;
}
