const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || `${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`);
const root = path.resolve(__dirname, '..');
const url = process.env.HERIN_URL || 'http://127.0.0.1:5174';
const fixture = path.join(__dirname, 'fixtures/Biology-course.pdf');
const results = [];
const ok = name => {results.push(name);console.log('PASS',name);};
(async()=>{
 const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
 const context = await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 page.on('console',msg=>{if(msg.type()==='error') errors.push(msg.text());});
 await page.goto(url+'/#/pdfs');
 await page.locator('input[type=file]').setInputFiles(fixture);
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('studydesk:pdfs')||'[]').some(p=>p.status==='ready'),{},{timeout:60000});
 const data=await page.evaluate(()=>({pdfs:JSON.parse(localStorage.getItem('studydesk:pdfs')),study:JSON.parse(localStorage.getItem('herin:study')),notes:JSON.parse(localStorage.getItem('studydesk:notes')),texts:JSON.parse(localStorage.getItem('studydesk:extractedTexts'))}));
 const id=data.pdfs[0].id;
 assert.equal(data.texts[id].pages.length,24);
 assert.equal(new Set(data.study.flashcards.map(c=>c.sourcePage)).size,24);
 assert.ok(data.study.flashcards.length>24);
 assert.ok(data.study.quizQuestions.some(q=>q.type==='multiple'));
 assert.ok(data.study.quizQuestions.some(q=>q.type==='enumeration'));
 assert.ok(data.study.quizQuestions.some(q=>q.type==='identification'));
 assert.ok(data.notes[id].content.includes('## Page 24'));
 ok(`24-page import: ${data.study.flashcards.length} cards, ${data.study.quizQuestions.length} questions; every page covered`);
 await page.reload();
 await page.getByText('Biology-course.pdf',{exact:true}).click();
 await page.locator('.pdf-text-layer span').first().waitFor();
 assert.ok(await page.locator('.study-note h3').count()>=24);
 assert.ok(await page.locator('.pdf-render canvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return d.some((v,i)=>i%4!==3 && v<200);}));
 ok('PDF and formatted note reopen; rendered canvas is nonblank');
 await page.getByRole('button',{name:'Next page',exact:true}).click();
 await page.getByText('Page 2 of 24',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();
 await page.getByRole('button',{name:'Fit width',exact:true}).click();
 await page.locator('.pdf-text-layer span').first().waitFor();
 await page.locator('.pdf-text-layer').evaluate(el=>{const span=el.querySelector('span');const range=document.createRange();range.selectNodeContents(span);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
 await page.getByRole('button',{name:'PDF Yellow highlight',exact:true}).click();
 await page.reload();
 assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('studydesk:highlights'))[id].length,id),1);
 await page.getByRole('button',{name:'Next page',exact:true}).click();
 await page.locator('.pdf-overlay > div').first().waitFor();
 const before=await page.locator('.pdf-overlay > div').first().getAttribute('style');
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();
 assert.equal(await page.locator('.pdf-overlay > div').first().getAttribute('style'),before);
 ok('PDF highlight survives immediate refresh, page changes, and zoom');
 await page.getByRole('button',{name:'Edit note',exact:true}).click();
 await page.getByRole('textbox',{name:'Your notes for this file'}).fill('# Edited study note\n\nKeep this custom explanation.');
 await page.reload();
 await page.getByText('Keep this custom explanation.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Regenerate study materials',exact:true}).click();
 await page.waitForFunction(id=>JSON.parse(localStorage.getItem('studydesk:pdfs')).find(p=>p.id===id).status==='ready',id);
 await page.waitForFunction(()=>!document.querySelector('.generation-status'));
 const after=await page.evaluate(id=>({study:JSON.parse(localStorage.getItem('herin:study')),note:JSON.parse(localStorage.getItem('studydesk:notes'))[id]}),id);
 assert.equal(after.study.flashcards.length,data.study.flashcards.length);
 assert.equal(after.study.quizQuestions.length,data.study.quizQuestions.length);
 assert.ok(after.note.content.includes('Keep this custom explanation.'));
 ok('Regeneration is idempotent and preserves custom notes');
 await page.getByRole('button',{name:'Create clearer outline',exact:true}).click();
 await page.getByRole('button',{name:'Create outline',exact:true}).click();
 await page.locator('.study-note h3').first().waitFor();
 await page.getByRole('tab',{name:'Extracted text',exact:true}).click();
 await page.locator('.extracted-text').evaluate(el=>{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const node=w.nextNode();const range=document.createRange();range.setStart(node,0);range.setEnd(node,Math.min(15,node.length));const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
 // Both text and page highlighting are tested independently.
 const picker=page.locator('.hl-color-picker');
 await picker.waitFor();
 await picker.locator('button').first().click();
 await page.reload();
 const highlights=await page.evaluate(id=>JSON.parse(localStorage.getItem('studydesk:highlights'))[id],id);
 assert.ok(highlights.some(h=>h.source==='text'));
 ok('Extracted-text highlight persists after immediate refresh');
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download original',exact:true}).click();
 const file=await download;assert.equal(file.suggestedFilename(),'Biology-course.pdf');
 const saved=await file.path();assert.deepEqual(fs.readFileSync(saved),fs.readFileSync(fixture));
 ok('Original download bytes match the uploaded PDF');
 await page.goto(url+'/#/flashcards');
 await page.getByRole('button',{name:'Tap to reveal answer',exact:true}).first().click();
 await page.getByRole('button',{name:'Good',exact:true}).first().click();
 await page.reload();assert.ok(await page.getByText('Know',{exact:true}).count());
 await page.getByRole('button',{name:'Edit flashcard',exact:true}).first().click();
 await page.getByLabel('Question',{exact:true}).fill('What is the edited concept?');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.reload();await page.getByRole('heading',{name:'What is the edited concept?',exact:true}).waitFor();
 ok('Flashcard reveal, review progress, editing, and refresh persistence');
 await page.goto(url+'/#/quiz');
 for(const type of ['multiple','identification','enumeration']){
   await page.getByLabel('Question type').selectOption(type);
   const q=data.study.quizQuestions.find(q=>q.type===type);
   if(type==='multiple')await page.locator('.quiz-options button').filter({hasText:q.correctAnswer}).click();
   else {await page.locator('#quiz-answer').fill(q.correctAnswer);await page.getByRole('button',{name:'Check answer',exact:true}).click();}
   await page.getByRole('heading',{name:'Correct',exact:true}).waitFor();
 }
 ok('Multiple-choice, identification, and enumeration answer checks');
 await page.goto(url+'/#/settings');
 await page.getByLabel('Color mode',{exact:true}).selectOption('dark');
 await page.getByRole('button',{name:'Forest',exact:true}).click();
 await page.reload();assert.equal(await page.locator('html').getAttribute('data-mode'),'dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'forest');
 ok('Theme and dark mode persist');
 fs.mkdirSync(path.join(root,'previews'),{recursive:true});
 await page.goto(url+'/#/flashcards');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(300);await page.screenshot({path:path.join(root,'previews/Herin-dark.png'),animations:'disabled'});
 await page.goto(url+'/#/settings');await page.getByLabel('Color mode',{exact:true}).selectOption('light');await page.getByRole('button',{name:'Ocean',exact:true}).click();
 await page.goto(url+`/#/pdfs/${id}`);await page.evaluate(()=>scrollTo(0,0));await page.locator('.pdf-render canvas').waitFor();await page.waitForTimeout(500);await page.screenshot({path:path.join(root,'previews/Herin-notes.png'),animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 for(const route of ['/','/pdfs',`/pdfs/${id}`,'/notes','/flashcards','/quiz','/schedule','/settings']){
   await page.goto(url+'/#'+route);await page.waitForTimeout(250);
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow on ${route}`);
 }
 await page.goto(url+'/#/flashcards');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(300);await page.screenshot({path:path.join(root,'previews/Herin-mobile.png'),animations:'disabled'});
 ok('Eight routes fit a 390px phone viewport');
 assert.deepEqual(errors,[]);ok('No browser console errors or uncaught exceptions in tested flows');
 fs.writeFileSync(path.join(root,'tests/browser-results.json'),JSON.stringify({results,errors},null,2));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
